### ISSUE TITLE
Example on how to use this in React and ajax remote call?

### ISSUE THREAD

**Issue by oliverchoy** [arendjr/selectivity-react#1]
Can you kindly provide the actual usage in React please?

**Comment by nkkollaw** [comment]
Yup. Examples would be nice.

**Comment by arendjr** [comment]
Oops, sorry, this project should be deprecated :)

I've integrated React support into the main Selectivity project: Usage examples (including AJAX) can be found on the homepage: https://arendjr.github.io/selectivity/ and setup instructions are on the GitHub page: https://github.com/arendjr/selectivity
